### ISSUE TITLE
Other platforms

### ISSUE THREAD

**Issue by GambitPlayer90** [Thukyd/OpenAI-Assistant-RDR2-Poker#1]
Would this tool also work for any other platform ?

**Comment by Thukyd** [comment]
This client is specifically designed for OpenAI Assistants. Other platforms likely use different data structures. I suppose in most cases it's more efficient to write a separate client. However, it would depend on the platform in question.

**Comment by GambitPlayer90** [comment]
Ah yes sorry for my vague question. I have Access to OpenAI and have openAI key as well but you mentioned the RD2 game or whatever. Or can i just use it on other poker platforms well is what I meent.

**Comment by Thukyd** [comment]
Ah got it, you can.

The OpenAI folder contains the actual client to manage the assistant. [https://github.com/Thukyd/OpenAI-Assistant-Manager/tree/main/src/openai](url)

In "run" you define your assistant base config. 

In test is an unfinished example for this RDR2 poker Assistant. There is barely logic in it yet. I didn't find time to continue with it.
